/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restrauntelayechi;

/**
 *
 * @author ASUS
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        wholebackground = new javax.swing.JPanel();
        Mainmenu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AddACustomer = new javax.swing.JLabel();
        SearchAcustomer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AnalyticsCustomers = new javax.swing.JLabel();
        mainphoto = new javax.swing.JLabel();
        rest_and_eat = new javax.swing.JLabel();
        cashiermenu = new javax.swing.JPanel();
        AddFood = new javax.swing.JLabel();
        SearchFood = new javax.swing.JLabel();
        UpdateFood = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        AnalyticsFood = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Mainmenu1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AddACashier = new javax.swing.JLabel();
        SearchCashier = new javax.swing.JLabel();
        UpdateCashier = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        wholebackground.setBackground(new java.awt.Color(0, 102, 102));

        Mainmenu.setBackground(new java.awt.Color(255, 255, 255));
        Mainmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Add a customer");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Find a customer");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Update a customer");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Analytics");

        AddACustomer.setBackground(new java.awt.Color(0, 0, 102));
        AddACustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-property-100.png"))); // NOI18N
        AddACustomer.setPreferredSize(new java.awt.Dimension(512, 512));
        AddACustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddACustomerMouseClicked(evt);
            }
        });

        SearchAcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restrauntelayechi/icons8-search-48.png"))); // NOI18N
        SearchAcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchAcustomerMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restrauntelayechi/customer.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        AnalyticsCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restrauntelayechi/icons8-combo-chart-100.png"))); // NOI18N
        AnalyticsCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnalyticsCustomersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MainmenuLayout = new javax.swing.GroupLayout(Mainmenu);
        Mainmenu.setLayout(MainmenuLayout);
        MainmenuLayout.setHorizontalGroup(
            MainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainmenuLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(MainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainmenuLayout.createSequentialGroup()
                        .addGroup(MainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AnalyticsCustomers)
                            .addComponent(jLabel7)
                            .addGroup(MainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AddACustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel13)
                                .addGroup(MainmenuLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24))))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainmenuLayout.createSequentialGroup()
                        .addComponent(SearchAcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(MainmenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MainmenuLayout.setVerticalGroup(
            MainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddACustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(SearchAcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(AnalyticsCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainphoto.setBackground(new java.awt.Color(0, 102, 102));
        mainphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/people-sitting-cafe_52683-18704.jpg"))); // NOI18N

        rest_and_eat.setFont(new java.awt.Font("Roboto", 3, 36)); // NOI18N
        rest_and_eat.setForeground(new java.awt.Color(255, 255, 255));
        rest_and_eat.setText("Restaurant El Ayechi");

        cashiermenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        AddFood.setBackground(new java.awt.Color(0, 0, 102));
        AddFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-property-100.png"))); // NOI18N
        AddFood.setPreferredSize(new java.awt.Dimension(512, 512));
        AddFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddFoodMouseClicked(evt);
            }
        });

        SearchFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restrauntelayechi/icons8-search-48.png"))); // NOI18N
        SearchFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchFoodMouseClicked(evt);
            }
        });

        UpdateFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restrauntelayechi/icons8-bento-100.png"))); // NOI18N
        UpdateFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateFoodMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Find a meal");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Add a meal");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Update a meal");

        AnalyticsFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restrauntelayechi/icons8-combo-chart-100.png"))); // NOI18N
        AnalyticsFood.setText("jLabel9");
        AnalyticsFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnalyticsFoodMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("Analytics");

        javax.swing.GroupLayout cashiermenuLayout = new javax.swing.GroupLayout(cashiermenu);
        cashiermenu.setLayout(cashiermenuLayout);
        cashiermenuLayout.setHorizontalGroup(
            cashiermenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashiermenuLayout.createSequentialGroup()
                .addGroup(cashiermenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(cashiermenuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(AddFood, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(SearchFood, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cashiermenuLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)))
                .addGap(74, 74, 74)
                .addGroup(cashiermenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateFood)
                    .addGroup(cashiermenuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cashiermenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashiermenuLayout.createSequentialGroup()
                        .addComponent(AnalyticsFood, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashiermenuLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(44, 44, 44))))
        );
        cashiermenuLayout.setVerticalGroup(
            cashiermenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashiermenuLayout.createSequentialGroup()
                .addComponent(AddFood, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(cashiermenuLayout.createSequentialGroup()
                .addGroup(cashiermenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cashiermenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cashiermenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UpdateFood, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchFood, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashiermenuLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(AnalyticsFood, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cashiermenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Mainmenu1.setBackground(new java.awt.Color(255, 255, 255));
        Mainmenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Add a cashier");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Find a cashier");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Update a cashier");

        AddACashier.setBackground(new java.awt.Color(0, 0, 102));
        AddACashier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-property-100.png"))); // NOI18N
        AddACashier.setPreferredSize(new java.awt.Dimension(512, 512));
        AddACashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddACashierMouseClicked(evt);
            }
        });

        SearchCashier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restrauntelayechi/icons8-search-48.png"))); // NOI18N
        SearchCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchCashierMouseClicked(evt);
            }
        });

        UpdateCashier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restrauntelayechi/cashier.jpg"))); // NOI18N
        UpdateCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateCashierMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Mainmenu1Layout = new javax.swing.GroupLayout(Mainmenu1);
        Mainmenu1.setLayout(Mainmenu1Layout);
        Mainmenu1Layout.setHorizontalGroup(
            Mainmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mainmenu1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(Mainmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddACashier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mainmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(UpdateCashier)
                        .addGroup(Mainmenu1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(Mainmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(SearchCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel6)))))
                .addGap(19, 19, 19))
        );
        Mainmenu1Layout.setVerticalGroup(
            Mainmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mainmenu1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(AddACashier, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(SearchCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(37, 37, 37)
                .addComponent(UpdateCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout wholebackgroundLayout = new javax.swing.GroupLayout(wholebackground);
        wholebackground.setLayout(wholebackgroundLayout);
        wholebackgroundLayout.setHorizontalGroup(
            wholebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholebackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(wholebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wholebackgroundLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(wholebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashiermenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(wholebackgroundLayout.createSequentialGroup()
                                .addComponent(mainphoto)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wholebackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rest_and_eat)
                        .addGap(156, 156, 156)))
                .addComponent(Mainmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(896, 896, 896))
        );
        wholebackgroundLayout.setVerticalGroup(
            wholebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholebackgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(wholebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(wholebackgroundLayout.createSequentialGroup()
                        .addComponent(rest_and_eat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cashiermenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mainmenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wholebackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(wholebackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddACustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddACustomerMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        AddCustomerAdmin obj = new AddCustomerAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_AddACustomerMouseClicked

    private void SearchAcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchAcustomerMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        GetCustomerAdmin obj = new GetCustomerAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_SearchAcustomerMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        UpdateCustomerAdmin obj = new UpdateCustomerAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void AnalyticsCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnalyticsCustomersMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        CustomerAnalytics obj = new CustomerAnalytics();
        obj.setVisible(true);
    }//GEN-LAST:event_AnalyticsCustomersMouseClicked

    private void AddACashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddACashierMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        AddCashier obj = new AddCashier();
        obj.setVisible(true);
    }//GEN-LAST:event_AddACashierMouseClicked

    private void SearchCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchCashierMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        GetCashier obj = new GetCashier();
        obj.setVisible(true);
    }//GEN-LAST:event_SearchCashierMouseClicked

    private void UpdateCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateCashierMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        UpdateCashier obj = new UpdateCashier();
        obj.setVisible(true);
    }//GEN-LAST:event_UpdateCashierMouseClicked

    private void AddFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddFoodMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        AddFood obj = new AddFood();
        obj.setVisible(true);
    }//GEN-LAST:event_AddFoodMouseClicked

    private void SearchFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchFoodMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        GetFood obj = new GetFood();
        obj.setVisible(true);
    }//GEN-LAST:event_SearchFoodMouseClicked

    private void UpdateFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateFoodMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        UpdateFood obj = new UpdateFood();
        obj.setVisible(true);
    }//GEN-LAST:event_UpdateFoodMouseClicked

    private void AnalyticsFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnalyticsFoodMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        FoodAnalytics obj = new FoodAnalytics();
        obj.setVisible(true);
    }//GEN-LAST:event_AnalyticsFoodMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddACashier;
    private javax.swing.JLabel AddACustomer;
    private javax.swing.JLabel AddFood;
    private javax.swing.JLabel AnalyticsCustomers;
    private javax.swing.JLabel AnalyticsFood;
    private javax.swing.JPanel Mainmenu;
    private javax.swing.JPanel Mainmenu1;
    private javax.swing.JLabel SearchAcustomer;
    private javax.swing.JLabel SearchCashier;
    private javax.swing.JLabel SearchFood;
    private javax.swing.JLabel UpdateCashier;
    private javax.swing.JLabel UpdateFood;
    private javax.swing.JPanel cashiermenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainphoto;
    private javax.swing.JLabel rest_and_eat;
    private javax.swing.JPanel wholebackground;
    // End of variables declaration//GEN-END:variables
}
