/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restrauntelayechi;

/**
 *
 * @author ASUS
 */
public class CashierMenu extends javax.swing.JFrame {
    

    /**
     * Creates new form CashierMenu
     */
    public CashierMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        wholebackground = new javax.swing.JPanel();
        Mainmenu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AddACustomer = new javax.swing.JLabel();
        SearchAcustomer = new javax.swing.JLabel();
        updateCustomer = new javax.swing.JLabel();
        Order = new javax.swing.JLabel();
        mainphoto = new javax.swing.JLabel();
        rest_and_eat = new javax.swing.JLabel();
        moto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        wholebackground.setBackground(new java.awt.Color(0, 102, 102));

        Mainmenu.setBackground(new java.awt.Color(255, 255, 255));
        Mainmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Add a customer");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Find a customer");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Update a customer");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Order");

        AddACustomer.setBackground(new java.awt.Color(0, 0, 102));
        AddACustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-property-100.png"))); // NOI18N
        AddACustomer.setPreferredSize(new java.awt.Dimension(512, 512));
        AddACustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddACustomerMouseClicked(evt);
            }
        });

        SearchAcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restrauntelayechi/icons8-search-48.png"))); // NOI18N
        SearchAcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchAcustomerMouseClicked(evt);
            }
        });

        updateCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restrauntelayechi/customer.png"))); // NOI18N
        updateCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateCustomerMouseClicked(evt);
            }
        });

        Order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restrauntelayechi/icons8-bento-100.png"))); // NOI18N
        Order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MainmenuLayout = new javax.swing.GroupLayout(Mainmenu);
        Mainmenu.setLayout(MainmenuLayout);
        MainmenuLayout.setHorizontalGroup(
            MainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainmenuLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainmenuLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(MainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainmenuLayout.createSequentialGroup()
                        .addGroup(MainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Order)
                            .addComponent(jLabel7)
                            .addGroup(MainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AddACustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel13)
                                .addGroup(MainmenuLayout.createSequentialGroup()
                                    .addComponent(updateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24))))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainmenuLayout.createSequentialGroup()
                        .addComponent(SearchAcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        MainmenuLayout.setVerticalGroup(
            MainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddACustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(SearchAcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(23, 23, 23)
                .addComponent(updateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(Order, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        mainphoto.setBackground(new java.awt.Color(0, 102, 102));
        mainphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/people-sitting-cafe_52683-18704.jpg"))); // NOI18N

        rest_and_eat.setFont(new java.awt.Font("Roboto", 3, 36)); // NOI18N
        rest_and_eat.setForeground(new java.awt.Color(255, 255, 255));
        rest_and_eat.setText("Restaurant El Ayechi");

        moto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/good.jpg"))); // NOI18N
        moto.setText("jLabel9");

        javax.swing.GroupLayout wholebackgroundLayout = new javax.swing.GroupLayout(wholebackground);
        wholebackground.setLayout(wholebackgroundLayout);
        wholebackgroundLayout.setHorizontalGroup(
            wholebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholebackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(wholebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wholebackgroundLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(mainphoto)
                        .addGap(18, 18, 18)
                        .addComponent(moto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wholebackgroundLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(rest_and_eat, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        wholebackgroundLayout.setVerticalGroup(
            wholebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholebackgroundLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(wholebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wholebackgroundLayout.createSequentialGroup()
                        .addComponent(rest_and_eat)
                        .addGap(67, 67, 67)
                        .addComponent(mainphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wholebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(wholebackgroundLayout.createSequentialGroup()
                            .addComponent(moto, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(249, 249, 249))
                        .addComponent(Mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wholebackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wholebackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddACustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddACustomerMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        AddCustomer obj = new AddCustomer();
        obj.setVisible(true);
    }//GEN-LAST:event_AddACustomerMouseClicked

    private void SearchAcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchAcustomerMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        GetCustomer obj = new GetCustomer();
        obj.setVisible(true);
    }//GEN-LAST:event_SearchAcustomerMouseClicked

    private void updateCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateCustomerMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        UpdateCustomer obj = new UpdateCustomer();
        obj.setVisible(true);
    }//GEN-LAST:event_updateCustomerMouseClicked

    private void OrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        Order obj = new Order();
        obj.setVisible(true);
    }//GEN-LAST:event_OrderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddACustomer;
    private javax.swing.JPanel Mainmenu;
    private javax.swing.JLabel Order;
    private javax.swing.JLabel SearchAcustomer;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainphoto;
    private javax.swing.JLabel moto;
    private javax.swing.JLabel rest_and_eat;
    private javax.swing.JLabel updateCustomer;
    private javax.swing.JPanel wholebackground;
    // End of variables declaration//GEN-END:variables
}
